* Charge-pump output current vs control voltage -- generated by run_cp.sh, do not edit.
*
* ⛔ THIS BENCH EXISTS BECAUSE Icp WAS A CONSTANT IN A DOCUMENT AND NOT A MEASUREMENT.
* Every loop figure this block publishes is computed from Icp = 1 uA, "mirrored 1:1 from
* the harness bias". The mirror is 1:1 in WIDTH. It is not 1:1 in drain-source voltage:
* the diode-connected reference sits at its own Vgs while the output devices sit near the
* control node, and on 0.5 um devices that difference is worth more than half the current.
* A loop gain that is out by that factor moves the crossover by the same factor.
*
* Two copies of the cell, one steering UP (source) and one DOWN (sink), each with a 0 V
* ammeter in series with its vctrl pin, so the two branch currents are separable while both
* see the SAME swept control voltage. Steering both in one instance would measure only the
* difference, which is the one quantity that says nothing about compliance.
.lib @M@/cornerMOSlv.lib @MOS@
.lib @M@/cornerRES.lib @RES@
.include @M@/cap_cmomf.lib
.include $PDK_ROOT/ihp-sg13cmos5l/libs.ref/sg13cmos5l_stdcell/spice/sg13cmos5l_stdcell.spice
.global sub!
.include pll_cells.spice
.temp @TEMP@
Vdd  vdd 0 @VDD@
Vss  vss 0 0
Vsub sub! 0 0
* Each instance gets its own reference: one source feeding two diode-connected
* mirrors would split between them and measure half the current twice.
Ib1 0 ib1 DC 250n
Ib2 0 ib2 DC 250n
Vup1 up1 0 @VDD@
Vdn1 dn1 0 0
Vup2 up2 0 0
Vdn2 dn2 0 @VDD@
Xcp1 up1 dn1 ib1 vc1 vdd vss charge_pump
Vm1  vc1 vctrl 0
Xcp2 up2 dn2 ib2 vc2 vdd vss charge_pump
Vm2  vc2 vctrl 0
Vctrl vctrl 0 0
.control
  dc Vctrl 0 @VDD@ 0.01
  wrdata pvt/@TAG@.csv i(Vm1) i(Vm2)
.endc
.end
