* tb_pll_lock corner point -- generated by run_lock.sh, do not edit directly.
* Closed-loop acquisition, mixed level.
*
* ⛔ THE BEHAVIOURAL VCO IS A CORNER, NOT A CONSTANT. F0/KVCO/VC0 below describe the ring
* at ONE process, temperature and rail, and the fixed-parameter version of this bench
* reported a single lock time for the whole block from the tt curve. That was tolerable
* while lock read 4 us against a 20 us limit; sizing the loop to respect its own f_ref/10
* bound spent most of that margin, so the corner spread is now the question. Each point
* here is placed at the SLOWEST output the part can be asked for -- N x f_ref at the bottom
* of the reference range -- with the local Kvco the tuning sweep measured there.
*
* Everything in the loop is the real cell -- PFD, charge pump, loop filter, divider --
* except the VCO, which is behavioural. That is deliberate, not a shortcut: a
* transistor-level ring has to be integrated at picosecond steps while the loop settles
* over tens of microseconds, which is seven orders of magnitude apart. A run of the full
* transistor loop reached 18 ns of a 30 us target. Loop dynamics are what this bench is
* for, and the behavioural VCO is matched to the MEASURED tuning curve of the real ring.
*
* VCO model: f(vctrl) = F0 + KVCO*(vctrl - VC0), taken from tb_vco_sweep on the loaded
* ring around the N=16 / 256 MHz operating point, which is the highest-Kvco corner and so
* the most aggressive loop gain among the selectable settings.
*
* Phase is integrated by a capacitor driven by a current equal to the instantaneous
* frequency, so v(ph) is the cycle count; the output is a square wave off its fraction.
.lib @M@/cornerMOSlv.lib @MOS@
.lib @M@/cornerRES.lib @RES@
.include @M@/cap_cmomf.lib
.include $PDK_ROOT/ihp-sg13cmos5l/libs.ref/sg13cmos5l_stdcell/spice/sg13cmos5l_stdcell.spice
.global sub!
* pll_cells.spice holds the real .subckt definitions, extracted from the top-level
* netlist. Including a sub-cell netlisted as TOP does not work: xschem comments out its
* own .subckt line, so the devices land at top scope instead of defining a subcircuit.
.include pll_cells.spice

.param F0=@F0@ KVCO=@KVCO@ VC0=@VC0@
.temp @TEMP@

Vdd  vdd  0 @VDD@
Vss  vss  0 0
Vsub sub! 0 0
* ⛔ 250 nA, NOT 1 uA. The loop filter is sized against the pump current this produces,
* and required capacitance scales with it: at the 1 uA reference the measured pump delivers
* 1.16-2.26 uA and a filter holding 45 degrees costs 15,908 um2, against 6,980 um2 here.
* This is the harness ibias1_250n rail rather than ibias1u_*.
Ibias 0 ibias DC 250n

Vref ref 0 PULSE(0 @VDD@ 5n 200p 200p 3n 62.5n)
Vpor  porb 0 PWL(0 0 20n 0 21n @VDD@ 1 @VDD@)
Vrstb rstb 0 PWL(0 0 20n 0 21n @VDD@ 1 @VDD@)
Vn0 nsel0 0 @VDD@
Vn1 nsel1 0 @VDD@

* --- behavioural VCO: phase integrator + square-wave slicer ---
* CLAMPED. A bare linear Kvco model goes NEGATIVE below vctrl ~0.545 V, and a negative
* frequency makes the phase integrator run backwards -- the divider then speeds up as
* vctrl falls, which is positive feedback that exists only in the model. The real ring
* saturates instead. Clamping to the measured band keeps the model physical wherever the
* loop wanders during acquisition.
Gph  0 ph  cur = 'min(max(F0 + KVCO*(V(vctrl) - VC0), 20e6), @FMAX@)'
Cph  ph 0 1
Rph  ph 0 1e12
* A hard slicer (tanh with high gain) makes this stiff: the solver is forced to resolve
* every VCO edge at picosecond scale and a 40 us run managed 46 ns. A plain sine still
* drives the divider's first flop rail to rail and integrates far more cheaply.
Bvco vco_out 0 V = '@VHALF@ + @VHALF@*sin(6.283185307*V(ph))'

* --- the real blocks ---
Xpfd ref div_out porb up dn vdd vss pfd
Xcp  up dn ibias vctrl vdd vss charge_pump
Xlf  vctrl vss loop_filter
Xdiv vco_out rstb nsel0 nsel1 div_out vdd vss divn

* start below the lock point but inside the valid tuning band, so this is a real
* pull-in rather than a excursion through a region the model cannot represent
.ic v(ph)=0 v(vctrl)=@VCSTART@

.control
* ⛔ THE TIMESTEP AND THE WINDOW ARE BOTH PER-CORNER, and both are validated rather than
* chosen. 100 ps over 24 us is ~4 hours a corner here, which makes an 18-corner sweep a
* thing nobody runs -- and a measurement nobody runs is a measurement that does not exist.
* 250 ps still resolves the VCO sine (15 points per cycle at 256 MHz); run_lock.sh proves
* it on the corner whose answer is already known before trusting it on any other.
* The window has to contain the settling it is looking for: acquisition scales with the
* loop gain, and the slow corners have half the gain of the typical one.
  tran @TSTEP@ @TSTOP@ uic
  meas tran vs1 FIND v(vctrl) AT=@T1@
  meas tran vs2 FIND v(vctrl) AT=@T2@
  meas tran vs3 FIND v(vctrl) AT=@T3@
  meas tran vs4 FIND v(vctrl) AT=@T4@
  meas tran vs5 FIND v(vctrl) AT=@T5@
  meas tran vs6 FIND v(vctrl) AT=@T6@
  meas tran vs7 FIND v(vctrl) AT=@T7@
  meas tran vs8 FIND v(vctrl) AT=@T8@
  wrdata pvt/@TAG@.csv v(vctrl)
.endc
.end
