* VCO PVT point -- generated by run_pvt.sh, do not edit directly.
.lib @M@/cornerMOSlv.lib @MOS@
.lib @M@/cornerRES.lib @RES@
.include /foss/pdks/ihp-sg13cmos5l/libs.ref/sg13cmos5l_stdcell/spice/sg13cmos5l_stdcell.spice
.global sub!
.include ../sim/netlist/rosc_vco.spice
.temp @TEMP@
Vdd   vdd   0 1.2
Vss   vss   0 0
Vsub  sub!  0 0
Vctrl vctrl 0 @VC@
.ic v(n1)=0
.control
  tran 20p 600n uic
  meas tran per4 TRIG v(n1) VAL=0.6 RISE=3 TARG v(n1) VAL=0.6 RISE=7
.endc
.end
