* VCO PVT point -- generated by run_pvt.sh, do not edit directly.
.lib @M@/cornerMOSlv.lib @MOS@
.lib @M@/cornerRES.lib @RES@
.include $PDK_ROOT/ihp-sg13cmos5l/libs.ref/sg13cmos5l_stdcell/spice/sg13cmos5l_stdcell.spice
.global sub!
.include ../sim/netlist/rosc_vco.spice
.temp @TEMP@
* The supply is a SWEPT corner, not a constant. This block runs entirely from the 1.2 V
* rail -- the proposal assumed a 3.3 V analog core, which the design moved away from -- and
* until 2026-09-02 this bench pinned it at exactly 1.2 V, so 27 PVT corners never once
* exercised the rail the whole circuit depends on.
Vdd   vdd   0 @VDD@
Vss   vss   0 0
Vsub  sub!  0 0
Vctrl vctrl 0 @VC@
.ic v(n1)=0
.control
  tran 20p 600n uic
  meas tran per4 TRIG v(n1) VAL=0.6 RISE=3 TARG v(n1) VAL=0.6 RISE=7
.endc
.end
